### ISSUE TITLE
Error on no provided parameters

### ISSUE THREAD

**Issue by ProfiiQus** [ProfiiQus/NextLib#2]
If there is defined a parameter, however the player hasn't entered it, error occurs:
```
[12:38:16] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'sun' in com.github.profiiqus.nextlib.command.Command(sun)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:776) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1931) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1770) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1751) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1125) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at com.github.profiiqus.nextlibtest.NextLibTest.lambda$onEnable$0(NextLibTest.java:26) ~[?:?]
        at com.github.profiiqus.nextlib.command.Command.execute(Command.java:93) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:3241-Spigot-6c1c1b2-1492826]
        ... 18 more
```

**Comment by ProfiiQus** [comment]
Should be fixed as of f27564ad5a032f7f133eb67e23fcc1be9f3421b5
